name: replication_project

channels:
  - conda-forge

dependencies:
  - python       = 3.9.4
  - numpy        = 1.20.3
  - pandas       = 1.2.4
  - jupyterlab   = 3.0.16
  - matplotlib   = 3.4.2
  - seaborn      = 0.11.1
  - dowhy        = 0.6
  - scipy        = 1.6.3
  - statsmodels  = 0.12.2
  - pip          = 21.1.2
  - scikit-learn = 0.24.2
  - econml       = 0.11.1
  

  - pip:
    - stargazer


